<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-05-08 17:23
=======
# Generated by Django 5.0.4 on 2024-05-08 17:12
>>>>>>> 87de94c0023a12c1b80f29ccb21a7732190f86a7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('jobs', '0002_delete_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
