# Generated by Django 5.0.4 on 2024-05-09 12:02

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_experiences_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
