# Generated by Django 5.0.4 on 2024-05-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_application_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(max_length=1000),
        ),
    ]
