# Generated by Django 5.0.4 on 2024-05-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_application_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='contact_bool',
            field=models.BooleanField(default=False),
        ),
    ]
