# Generated by Django 5.0.4 on 2024-05-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_references_contact_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='contact_bool',
            field=models.BooleanField(),
        ),
    ]
