<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-05-08 17:23
=======
# Generated by Django 5.0.4 on 2024-05-08 17:08
>>>>>>> 87de94c0023a12c1b80f29ccb21a7732190f86a7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='user',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Individual',
        ),
    ]
