<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-05-08 17:23
=======
# Generated by Django 5.0.4 on 2024-05-08 17:08
>>>>>>> 87de94c0023a12c1b80f29ccb21a7732190f86a7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='default', upload_to='profile_images')),
                ('address', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
