# Generated by Django 5.0.4 on 2024-05-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_remove_individual_id_remove_individual_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='owner',
            new_name='parent_user',
        ),
    ]
