# Generated by Django 5.0.4 on 2024-05-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_rename_owner_individual_parent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/avatars/', verbose_name='profile picture'),
        ),
    ]
