# Generated by Django 5.0.4 on 2024-05-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_alter_individual_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='pic',
            field=models.ImageField(upload_to='images/', verbose_name='profile picture'),
        ),
    ]
