<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-05-08 18:36
=======
# Generated by Django 5.0.4 on 2024-05-09 13:28
>>>>>>> 79f22f3ad5f92a779d47efd1333df357c79f2430

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
    ]
