# Generated by Django 5.0.4 on 2024-05-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cover_image',
            field=models.ImageField(default='default', upload_to='static/companies/cover_images'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='default', upload_to='static/companies/logo_images'),
        ),
    ]
