# Generated by Django 5.0.4 on 2024-05-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_cover_image_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
